# This is a basic workflow to help you get started with Actions

name: CI/Build/MacOS

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, pull_request ]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
  pull_request:
    branches: [ main, pull_request ]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this is darwin-amd64
  build-macos-x86_64:

    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build and test everything
        run: uname -a && bazelisk build //... && bazelisk test //... && bazelisk build //:promtool
